version: '3.8'
services:
  app:
    image: ${APP_IMAGE}
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    restart: on-failure
    volumes:
      - app_data:/mnt/shared/app-data
    environment:
      - MODEL_SERVICE_URL=http://model-service:${MODEL_SERVICE_CONTAINER_PORT}
      - ENV=production
      # - SECRET_PASSWORD_FILE=/run/secrets/app_password
    # secrets:
    #   - app_password
    depends_on:
      - model-service

  model-service:
    image: ${MODEL_SERVICE_IMAGE} 
    # Poor: Services other than app-service are accessible on localhost So commented this
    # ports:
    #   - "5001:5001"
    restart: on-failure

    # listening port of the model-service can be conﬁgured through an ENV variable
    volumes:
      - model_service_data:/app/models
      - model_service_data:/app/bow
    environment:
      - PORT=${MODEL_SERVICE_CONTAINER_PORT}


volumes:
  model_service_data:
  app_data:

  # secrets:
  #   my_secret:
  #     file: ./my_secret.txt