version: '3.8'

services:
  app:
    image: ghcr.io/remla25-team2/app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./app-data:/app/data #not used for now
    environment:
      - ENV=production #not used for now
    restart: on-failure