version: '3.8'
services:
  app:
    image: ghcr.io/remla25-team2/app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./app-data:/app/data
    environment:
      - ENV=production
      - MODEL_SERVICE_URL=http://model-service:5001
    depends_on:
      - model-service

  model-service:
    image: ghcr.io/remla25-team2/model-service:latest
    ports:
      - "5001:5001"
    restart: on-failure
