appVersion: "0.1.0"

replicaCount: 1

app:
  image:
    repository: ghcr.io/remla25-team2/app
    tag: latest
  service:
    port: 5000
  modelServiceUrl: "http://my-app-model-service:5001"
  hostPathVolume:
    path: /mnt/shared/app-data

modelService:
  image:
    repository: ghcr.io/remla25-team2/model-service
    tag: latest
  service:
    port: 5001
  hostPathVolume: 
    modelPath: /mnt/shared/model-service/models
    bowPath: /mnt/shared/model-service/bow


experiment:
  enabled: false
  versions:
    v1:
      weight: 90
      image:
        repository: ghcr.io/remla25-team2/app
        tag: v0.1.5  # Baseline version
    v2:
      weight: 10
      image:
        repository: ghcr.io/remla25-team2/app
        tag: v0.2.1  # Experiment version
      modelImage:
        repository: ghcr.io/remla25-team2/model-service
        tag: v0.2.0


config:
  message: "Hello from Helm!"

ingress:
  host: "app.local"


rateLimit:
  unit: minute
  requests_per_unit: 10
  service:
    name: ratelimit
    port: 8081
    containerPort: 8081
  image:
    repository: envoyproxy/ratelimit
    tag: v1.4.0