appVersion: "0.1.0"

replicaCount: 1

app:
  image:
    repository: ghcr.io/remla25-team2/app
    tag: latest
  service:
    port: 5000
  modelServiceUrl: "http://my-app-model-service:5001"
  hostPathVolume:
    path: /mnt/shared/app-data

modelService:
  image:
    repository: ghcr.io/remla25-team2/model-service
    tag: latest
  service:
    port: 5001

experiment:
  enabled: false
  versions:
    v1:
      weight: 90
      image:
        repository: ghcr.io/remla25-team2/app
        tag: v0.1.5  # Baseline version
    v2:
      weight: 10
      image:
        repository: ghcr.io/remla25-team2/app
        tag: v0.2.1  # Experiment version


config:
  message: "Hello from Helm!"

secret:
  password: "your-base-secret"

ingress:
  host: "app.local"

