appVersion: "0.1.0"

replicaCount: 1

app:
  image:
    repository: ghcr.io/remla25-team2/app
    tag: latest
  service:
    port: 5000
  modelServiceUrl: "http://my-app-model-service:5001"
  hostPathVolume:
    path: /mnt/shared/app-data

modelService:
  image:
    repository: ghcr.io/remla25-team2/model-service
    tag: latest
  service:
    port: 5001

experiment:
  enabled: true
  versions:
    v1:
      weight: 70
      image:
        repository: ghcr.io/remla25-team2/app
        tag: 0.2.1  # Baseline version
    v2:
      weight: 30
      image:
        repository: ghcr.io/remla25-team2/app
        tag: latest


config:
  message: "Hello from Helm!"

ingress:
  host: "app.local"


rateLimit:
  unit: minute
  requests_per_unit: 200
  service:
    name: ratelimit
    port: 8081
    containerPort: 8081
  image:
    repository: envoyproxy/ratelimit
    tag: v1.4.0