apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-model-service
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.modelService.service.port }}
      targetPort:  {{ .Values.modelService.service.port }}
      protocol: TCP
      
  selector:
    app.kubernetes.io/component: model-service
    app.kubernetes.io/instance: {{ .Release.Name }}