apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}-secret-placeholder
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
type: Opaque
stringData:
  README: |
    This is a placeholder. Create the actual secret with:
    kubectl create secret generic app-secrets --from-literal=password=YOUR_SECRET_PASSWORD