apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-app.fullname" . }}-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "my-app.name" . }}
  endpoints:
    - port: http
      path: /metrics
