global:
  resolve_timeout: 5m
route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: "email-alert"
receivers:
  - name: "email-alert"
    email_configs:
      - to: "your-email@example.com"
        from: "alertmanager@example.com"
        smarthost: "smtp.example.com:587"
        auth_username: "your-username"
        auth_password: "your-password"
