groups:
  - name: example
    rules:
      - alert: HighRequestRate
        expr: rate(http_requests_total[1m]) > 15
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "The request rate is above 15 requests per minute for the last 2 minutes."
